#!/bin/bash

SNES9X_VOL_FILE=~/.xbmc/snes9x_volume

# record current master volume settings
XBMC_VOL=`aumix -q | grep vol | awk '{print $2 }'`

# load zsnes volume settings
if [ -f $SNES9X_VOL_FILE ]
then
	. $SNES9X_VOL_FILE
fi

if [ ! -z $SNES9X_VOL ]
then
	aumix -v $SNES9X_VOL
fi

# start zsnes with zsnes qjoypad profile
qjoypad SNES9X

/usr/games/snes9x-gtk "$*"

# switch back to xbmc profile

qjoypad XBMC

# switch back volume settings
SNES9X_VOL=`aumix -q | grep vol | awk '{print $2 }'`
echo "SNES9X_VOL=$SNES9X_VOL" > $SNES9X_VOL_FILE

aumix -v $XBMC_VOL
