#! /bin/bash
# Launch XBMC in windowed mode, then use wmctrl to remove the titlebar
 
# Select display 1
#export DISPLAY=:0
# if needed
#export DISPLAY=`ps | grep X | grep -v grep | perl -e '$line = <STDIN>; $line =~ /\ (:\d+)/; print $1;'`
 
# start qjoypad with xbmc default layout
qjoypad XBMC &

# set volume to 100
aumix -v 100

while true
do
#	/opt/xbmc/bin/xbmc &
	xbmc &
 
	# Wait for the XBMC window to appear
	status=0
	while [ $status -eq 0 ]
	do
		sleep 1
		status=`wmctrl -x -l | grep "XBMC Media Center" | wc -l | awk '{print $1}'`
	done
 
	# Force XBMC window to fullscreen
	wmctrl -x -r XBMC Media Center.XBMC Media Center -b toggle,fullscreen

	wait
done
